POST http://localhost:3001/user/register 
Content-Type: application/json

{
  "name": "sandy",
  "email": "sandy@example.com",
  "password": "sandy@1",
  "role": "admin"
}

###
POST http://localhost:3001/user/login 
Content-Type: application/json

{
  "email": "sandy@example.com",
  "password": "sandy@1"
}

###
GET http://localhost:3001/user/infor
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwMTk0NjM3N2UwZDUzODk3ZDk4Nzk0YSIsImlhdCI6MTYxMjI3MzIwMCwiZXhwIjoxNjEyMzU5NjAwfQ.kZJVr9R2PSR7Ybw2lZVH1XymAJ_tdJnGntBXC2oKhvk

###
GET http://localhost:3001/user/refresh_token

###
POST http://localhost:3001/api/category
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwMTk0NjM3N2UwZDUzODk3ZDk4Nzk0YSIsImlhdCI6MTYxMjI3MzQ3OSwiZXhwIjoxNjEyMzU5ODc5fQ.aWyoqxn7cxHmFxE4b8j3x6MQKDZOxu3p1vSDmDspP3s

{
  "name": "third product"
}

###
GET http://localhost:3001/api/category

###
DELETE http://localhost:3001/api/category/6019584c16285fdbc3d7a7a0
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwMTk0NjM3N2UwZDUzODk3ZDk4Nzk0YSIsImlhdCI6MTYxMjI3MzQ3OSwiZXhwIjoxNjEyMzU5ODc5fQ.aWyoqxn7cxHmFxE4b8j3x6MQKDZOxu3p1vSDmDspP3s

###
PUT http://localhost:3001/api/category/6019583d16285fdbc3d7a79f
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwMTk0NjM3N2UwZDUzODk3ZDk4Nzk0YSIsImlhdCI6MTYxMjI3MzQ3OSwiZXhwIjoxNjEyMzU5ODc5fQ.aWyoqxn7cxHmFxE4b8j3x6MQKDZOxu3p1vSDmDspP3s

{
  "name": "updated second product"
}